### ISSUE TITLE
"takedown notice"

### ISSUE THREAD

**Issue by frangio68** [nikodallanoce/ComputationalMathematics#71]
Salve.

Stiamo avendo problemi con gruppi di CM che continuano ad "ispirarsi un po' troppo" al materiale che trovano su questo repository. Questo crea disagi a noi, ma sopratutto ai gruppi stessi quando inevitabilmente la cosa viene fuori. Sarebbe un gesto responsabile da parte vostra rendere privato (o cancellare) il repository per evitare il problema. Non possiamo imporlo, ma vi chiediamo di considerare con attenzione la richiesta. Se volete discuterne ovviamente siamo disponibili.

Federico Poloni, Antonio Frangioni

**Comment by nikodallanoce** [comment]
Salve,

Ci siamo confrontati con @RistoAle97 e @simone-rizzo. Lo scopo di avere una repository pubblica è quello di fornire un'implementazione degli algoritmi, come accade normalmente con il codice su Git. Per quanto concerne questo aspetto, per chi vuole copiare, non è tanto differente farlo dalla nostra repository oppure da qualche sito web. Inoltre, il codice è stato scritto interamente da noi, senza copiare altri, che ci ha portato via tanto tempo prima di essere completato. Crediamo anche che, condividere tali progetti, sia ben visto dalle aziende o dai recruiter.

Cercando di essere coerenti con quanto detto, secondo noi sarebbe giusto rimuovere il report, per disincentivare gli studenti del corso di CM a limitarsi a copiare e basta. Terremo il codice, che potrebbe comunque essere copiato da qualche altra parte su internet.

Può essere un buon compromesso?

**Comment by RistoAle97** [comment]
Buon pomeriggio,

> Direi che rimuovere il report sia per noi la cosa fondamentale.

come richiesto, abbiamo rimosso la directory contenente il report ed i vari file latex ad esso legati con la pull request #72  . Abbiamo notato, inoltre, che nella cronologia delle commits il pdf del report non può essere mostrato.
Se la questione è risolta, passo a chiudere la issue.

**Comment by frangio68** [comment]
>> Direi che rimuovere il report sia per noi la cosa fondamentale.
> come richiesto, abbiamo rimosso la directory contenente il report ed i vari file latex ad esso legati con la pull request #72 . Abbiamo notato, inoltre, che nella cronologia delle commits il pdf del report non può essere mostrato.

... ma il LaTeX si? Perché in quel caso in realtà il problema continua a persistere.

	Saluti

	Antonio

**Comment by RistoAle97** [comment]
@frangio68 dovrei aver risolto, ho dovuto usare `git filter-repo --invert-paths --path --force report/` per eliminare le commit contenenti riferimenti a qualunque file nella directory del report per poi sistemare qualcosa a mano, chiedo conferma anche a @nikodallanoce se i file nelle altre directory non sono stati modificati.
Per sicurezza elimino i branch che non siano il main, in modo che ogni traccia del report sia rimossa.

**Comment by frangio68** [comment]
> @frangio68 dovrei aver risolto, ho dovuto usare git filter-repo --invert-paths --path --force report/ per eliminare le commit contenenti riferimenti a qualunque file nella directory della repo per poi sistemare qualcosa a mano, chiedo conferma anche a @nikodallanoce se i file nelle altre directory non sono stati alterati.
> Per sicurezza elimino i branch che non siano il main, in modo che ogni traccia del report sia rimossa.

Vi ringraziamo. Una volta che siete sicuri che i files non possano essere recuperati la issue può essere chiusa.

	Federico e Antonio

**Comment by nikodallanoce** [comment]
Controllato. Nella history non compaiono più i report, né PDF né LaTeX.

**Comment by RistoAle97** [comment]
@nikodallanoce Perfetto, passo a chiudere.
